name: alert_system
description: "A new Flutter project."

# The following line prevents accidental publication to pub.dev.
publish_to: 'none'

# Versioning for the app
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: ^3.6.0

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1  # Ensure compatibility with other Firebase packages
  firebase_database: ^11.3.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.2  # Fixed version conflicts
  fluttertoast: ^8.2.10
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  flutter_contacts: ^1.1.9+2
  flutter_background_messenger: ^0.0.2
  logger: ^2.5.0
  email_validator: ^3.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.3.0
  smooth_page_indicator: ^1.2.1
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.0
  url_launcher: ^6.2.1
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    
    - assets/images/shield.png
    - assets/images/sos.png
    - assets/images/travel-insurance.png
    - assets/images/add-user.png
    - assets/images/account.png
    - assets/images/document.png
