// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import  'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDezdrdTOS_arqcTPHnOk-WAktnun2vbZw",
      authDomain: "emergency-alert-cfa28.firebaseapp.com",
      projectId: "emergency-alert-cfa28",
      storageBucket: "emergency-alert-cfa28.firebasestorage.app",
      messagingSenderId: "798237308400",
      appId: "1:798237308400:web:2b6f5ca8033186a3a81935",
      measurementId: "G-YW350HWYQV"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyDezdrdTOS_arqcTPHnOk-WAktnun2vbZw",
      authDomain: "emergency-alert-cfa28.firebaseapp.com",
      projectId: "emergency-alert-cfa28",
      storageBucket: "emergency-alert-cfa28.firebasestorage.app",
      messagingSenderId: "798237308400",
      appId: "1:798237308400:web:2b6f5ca8033186a3a81935",
      measurementId: "G-YW350HWYQV"
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyDezdrdTOS_arqcTPHnOk-WAktnun2vbZw",
      authDomain: "emergency-alert-cfa28.firebaseapp.com",
      projectId: "emergency-alert-cfa28",
      storageBucket: "emergency-alert-cfa28.firebasestorage.app",
      messagingSenderId: "798237308400",
      appId: "1:798237308400:web:2b6f5ca8033186a3a81935",
      measurementId: "G-YW350HWYQV"
  );

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyDezdrdTOS_arqcTPHnOk-WAktnun2vbZw",
      authDomain: "emergency-alert-cfa28.firebaseapp.com",
      projectId: "emergency-alert-cfa28",
      storageBucket: "emergency-alert-cfa28.firebasestorage.app",
      messagingSenderId: "798237308400",
      appId: "1:798237308400:web:2b6f5ca8033186a3a81935",
      measurementId: "G-YW350HWYQV"
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyDezdrdTOS_arqcTPHnOk-WAktnun2vbZw",
      authDomain: "emergency-alert-cfa28.firebaseapp.com",
      projectId: "emergency-alert-cfa28",
      storageBucket: "emergency-alert-cfa28.firebasestorage.app",
      messagingSenderId: "798237308400",
      appId: "1:798237308400:web:2b6f5ca8033186a3a81935",
      measurementId: "G-YW350HWYQV"
  );
}
